service: demo-link-shortener

provider:
    name: aws
    region: eu-west-3
    runtime: provided.al2
    deploymentMethod: direct # fastest deployment method
    iam:
      role:
        statements:
          - Effect: Allow
            Action: events:PutEvents
            Resource: '*'

plugins:
  - serverless-lift
  - ./vendor/bref/bref

functions:
    entrypoint:
        handler: entrypoint.php
        description: 'API to register one or more links'
        environment:
          TABLE_NAME: ${construct:links.tableName}
          DOMAIN_NAME: 'https://link.test'
        layers:
            - ${bref:layer.php-81}
        events:
            - httpApi:
                method: 'POST'
                path: '/links'

    redirect:
        handler: index.php
        description: 'Redirect user to target URL'
        layers:
            - ${bref:layer.php-81}
        environment:
          BUCKET_NAME: ${construct:published-links.bucketName}
        events:
            - httpApi:
                  method: 'GET'
                  path: '/{id+}'

constructs:
  published-links:
    type: storage
  links:
    type: database/dynamodb-single-table

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
